apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-flask-kubernetes-sec
  labels:
    app: py-flask-kubernetes-sec
spec:
  selector:
    matchLabels:
      app: py-flask-kubernetes-sec
  replicas: 1
  template:
    metadata:
      labels:
        app: py-flask-kubernetes-sec
    spec:
      containers:
      - name: py-flask-kubernetes
        image: ghcr.io/sainithesh/py-flask-kubernetes:week3 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
            limits:
              ephemeral-storage: 256M
              memory: 256M
              cpu: 100m
            requests:
              ephemeral-storage: 256M
              memory: 256M
              cpu: 100m
      imagePullSecrets:
      - name: py-regcred
status: {}
        
---
apiVersion: v1
kind: Service
metadata:
  name: py-flask-kubernetes-sec
spec:
  selector:
    app: py-flask-kubernetes-sec
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8080


---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: py-flask-kubernetes-sec
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: py-flask-kubernetes-sec
    port: 8081
    host: py-flask-kubernetes-sec
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: jwt
          config: 
            jwks_urls:
            - >-
             https://bd7f2882trial.authentication.us10.hana.ondemand.com/token_keys


################### XSUAA ###################
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: py-flask-kubernetes-xsuaa-oidc
spec:
  serviceOfferingName: xsuaa
  servicePlanName: application

################### XSUAA SERVICE BINDING ###################
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: py-flask-kubernetes-xsuaa-service-binding
spec:
  serviceInstanceName: py-flask-kubernetes-xsuaa-oidc
  secretName: xsuaa-service-binding