name: publish

on: [push]

jobs:
  publish-py-flask-kubernetes-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PKG_SECRET }}

    - name: Build the py-flask-kubernetes Docker image
      run: |
        docker build . --tag ghcr.io/sainithesh/py-flask-kubernetes:latest
        docker run ghcr.io/sainithesh/py-flask-kubernetes:latest
        docker push ghcr.io/sainithesh/py-flask-kubernetes:latest
